# .github/workflows/release.yaml
# https://github.com/marketplace/actions/go-release-binaries
# https://web3.coach/golang-github-actions-release-binaries-tutorial
name: Release

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        goos: linux
        goarch: amd64
  release-mac-amd64:
    name: release mac/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          goos: darwin
          goarch: amd64
